# Generated by Django 5.0.3 on 2024-03-13 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5d5ef385-b5ac-410d-817c-20ad595fbca3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5d5ef385-b5ac-410d-817c-20ad595fbca3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5d5ef385-b5ac-410d-817c-20ad595fbca3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
